(ns hygaccess.regulatory
  "Regulatory-submission-STATUS TRACKING state machine for the low-cost
  hygiene/disinfectant commercialization actor.

  CRITICAL SCOPE BOUNDARY: this namespace tracks the REAL-WORLD status
  of the three regulatory dossier DRAFTS already prepared under
  `docs/regulatory/` (`india-cdsco-dossier.md`, `gcc-gso-dossier.md`,
  `asean-cosmetic-dossier.md`, per the SKU-to-dossier mapping in
  `docs/regulatory/README.md`) per (market, product-type) pair. It does
  NOT file anything with any real government/regulatory system -- there
  is no HTTP client here, no submission API, no auto-generated
  filing -- STATUS TRACKING ONLY. A human must independently supply the
  evidence (filer name, date, agency reference) for any consequential
  transition (`:submitted`/`:approved`/`:rejected`); this namespace and
  `hygaccess.governor` NEVER auto-generate, default, or infer that
  evidence. `:record-regulatory-submission-status` is NEVER a member of
  any phase's `:auto` set (see `hygaccess.phase`) -- always
  human-approval-gated via the existing `interrupt-before` mechanism,
  mirroring the permanent-manual pattern `:schedule-maintenance`
  already establishes, regardless of confidence.

  NON-BREAKING WIRING NOTE (see also README `Regulatory-submission
  tracking`): in a REAL deployment, an `:approved` regulatory-
  submission-status record here is intended to be the actual evidence
  behind a market's own `hygaccess.store/market-entry-approvals`
  boolean. This build deliberately does NOT wire that as a new HARD
  block on `:propose-market-entry` -- the six markets
  `hygaccess.store/sample-data!` already seeds `:approved? true`
  (IN/BD/ID/PH/SA/AE) and the 104 pre-existing tests asserting against
  them (and this build's own extension of that seed data) must keep
  passing unchanged, so retrofitting a HARD dependency here would be a
  breaking change to an already-shipped invariant. Instead,
  `market-approval-without-submission-warnings` below is a
  complementary, WARN-only, non-blocking consistency check --
  `hygaccess.governor/check` now always attaches its result under
  `:warnings` in the verdict map, surfacing the gap for a human
  go-to-market coordinator to close without holding or escalating any
  existing or new proposal because of it."
  (:require [clojure.string :as str]))

;; ----------------------------- state machine -----------------------------

(def statuses
  "The closed set of regulatory-submission-status values."
  #{:draft :counsel-review :submitted :agency-review :approved :rejected :withdrawn})

(def terminal-statuses
  "No transition leaves any of these three -- a decided/withdrawn
  submission stays decided."
  #{:approved :rejected :withdrawn})

(def transitions
  "The closed, ground-truth state-machine transition table:
  `:draft` -> `:counsel-review` -> `:submitted` -> `:agency-review` ->
  `:approved` | `:rejected` | `:withdrawn`. A proposal's own claimed
  `:to-status` is NEVER trusted on its own self-report;
  `hygaccess.governor/regulatory-transition-invalid-violations`
  independently looks up the CURRENT stored status (or `:draft` if this
  (market, product-type) pair has no record yet) in THIS table before
  allowing a single-step transition. No skipping states (e.g. `:draft`
  directly to `:submitted` is rejected -- counsel review is a mandatory
  intermediate step); no transitions out of a terminal status. Per this
  build's own scope, `:withdrawn` is reachable only from
  `:agency-review` (matching the exact chain this actor's task brief
  specifies) -- a real deployment MAY want early withdrawal from
  `:counsel-review`/`:submitted` too, but this build does not invent
  that beyond the given chain; see `docs/adr/` for this build's own
  extension record."
  {:draft          #{:counsel-review}
   :counsel-review #{:submitted}
   :submitted      #{:agency-review}
   :agency-review  #{:approved :rejected :withdrawn}
   :approved       #{}
   :rejected       #{}
   :withdrawn      #{}})

(defn valid-transition?
  "Is `from` -> `to` an allowed single-step transition in the closed
  `transitions` table?"
  [from to]
  (boolean (contains? (get transitions from #{}) to)))

;; ----------------------------- human-evidence discipline -----------------------------

(def consequential-statuses
  "Transitions INTO these three statuses require independently-supplied
  human evidence (`:filed-by`/`:filing-date`/`:agency-reference`) -- a
  real human counsel/filer's own claim of what happened, never
  defaulted or auto-generated by this actor."
  #{:submitted :approved :rejected})

(def evidence-keys [:filed-by :filing-date :agency-reference])

(defn- non-blank-string? [v] (and (string? v) (not (str/blank? v))))

(defn evidence-complete?
  "Ground-truth check: for a transition INTO a consequential status, are
  ALL THREE evidence fields present as non-blank strings in the
  proposal's own `:value`? Never defaulted -- an absent, nil, or
  blank/whitespace-only field is treated as missing evidence, not
  silently synthesized."
  [value]
  (every? #(non-blank-string? (get value %)) evidence-keys))

;; ----------------------------- non-breaking market-approval consistency WARNING -----------------------------

(defn market-approval-without-submission-warnings
  "Non-breaking, WARN-only (NEVER HARD-blocking, never escalating)
  consistency scan: for every country independently marked
  `:approved? true` in `hygaccess.store/market-entry-approvals`
  (`approved-countries`), does at least one regulatory-submission
  record on file (`regulatory-submissions`, any product-type) for that
  market carry `:status :approved`? See ns docstring 'NON-BREAKING
  WIRING NOTE' for why this is a warning, not a new HARD check, and for
  what a real deployment is intended to eventually enforce.

  `approved-countries` -- seq/set of ISO3166-alpha-2 codes independently
  marked `:approved? true` (the store's own ground truth, NOT a
  proposal's self-report).
  `regulatory-submissions` -- seq of all regulatory-submission records
  on file (each at least `{:market .. :status ..}`).

  Returns a vector of `{:rule :market-approved-without-regulatory-
  submission :market <code> :detail <str>}` maps, one per unbacked
  approved market, sorted by country code for deterministic output; an
  empty vector when every approved market already has at least one
  `:approved` submission record backing it."
  [approved-countries regulatory-submissions]
  (let [approved-by-market (set (map :market (filter #(= :approved (:status %)) regulatory-submissions)))]
    (vec
     (for [country (sort (set approved-countries))
           :when (not (contains? approved-by-market country))]
       {:rule :market-approved-without-regulatory-submission
        :market country
        :detail (str country " は market-entry-approvals で :approved? true だが、"
                     "対応する :approved 状態の regulatory-submission 記録が無い -- "
                     "実運用ではこの記録が承認の実証根拠となるべき (SOFT warning, 非block, 非escalate)")}))))
